comments:
  enabled: True
  percentage: 25
  Photo:
    - Impresionante!
    - Enhorabuena gran trabajo
    - Awesome!
  Video:
    - Great take
    - Amazing flow

follow:
  enabled: True
  percentage: 10
  times: 2
  interact:
    - natgeo

users:
  ignored:
    - random_user
  dont_include:
    - friend1

exclude:
  - '#exactmatch'
  - '[startswith'
  - ']endswith'
  - 'broadmatch'
