comments:
  enabled: True
  percentage: 25
  Photo:
    - Impresionante!
    - Enhorabuena gran trabajo
    - Awesome!
  Video:
    - Great take
    - Amazing flow

follow:
  set:
    enabled: True
    percentage: 10
    times: 2
  kwargs:
    amount: 10
    randomize: True
  interact:
    - natgeo

like:
  enabled: True
  percentage: 70
  tags:
    - tag1
  locations:
    - 215101523
  dont:
    - '#exactmatch'
    - '[startswith'
    - ']endswith'
    - 'broadmatch'
  ignored:
    - random_user
  ignore_if_contains:
    - random

users:
  dont_include:
    - friend1
  track:
    - dcrainmaker
